Use Case 7: Feature/Download CSV options
TCU-Instructional-AI/classifAI pull request #10
Opened 2023-11-01 03:03 UTC by J4ninja

## Type of Change

New Feature Download CSV according to selected checkbox options

## Context

Use Case 7 
Issue #7 

## Changes Made

- Added checkbox to select all other checkboxes
- Added Start Time checkbox 
- Added End Times checkbox
- Added Speaker checkbox
- Added isQuestion Label Checkbox
- Added Text Checkbox
- Added Only Questions Checkbox
- Renamed button to 'Export CSV'
- Handled file name input onBlur instead of onChange to reduce latency

## Screenshots

![Screenshot 2023-10-31 at 2 17 53 PM](https://github.com/TCU-Instructional-AI/classifAI/assets/34970564/c324bc58-2092-4741-b560-d9005f767a62)

## Checklist

- [x] I have tested these changes locally
- [x] I have updated the documentation (use case Issue board, if applicable
- [ ] I have added unit tests, if applicable

2023-11-01 04:22 UTC, jhmejia requested changes

2023-11-01 04:22 UTC, jhmejia commented on frontend/src/Main/Submission/submission.js
> +    const lines = transcript.match(sentenceRegex);
nit: maybe split this into a smaller function like this: 

```typescript
// Split the transcript into an array of sentences (keeping the punctuation marks)
function getSentences(transcript) {
  const sentenceRegex = /([^.!?]+[.!?])/g;
  return transcript.match(sentenceRegex);
}
```

2023-11-01 04:22 UTC, jhmejia commented on frontend/src/Main/Submission/submission.js
> +      if (startTimeBox && push) {
You should just return early if `push` is false. That way you can [reuse your code](https://github.com/TCU-Instructional-AI/classifAI/pull/10/files#diff-dce5476922e05a134470b560c1df54167900bd8ac6b79d7c3f108d6f1b591e14R147-R149)

Now that you have the same code, maybe you can modularly split it up into a separate function like this.  Remember, [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

```javascript
function createCSVRow(sentence, csvColumns, questionsBox) {
  const data = [];
  for (const csvColumn of csvColumns) {
    switch (csvColumn) {
      case 'Start Time':
        data.push(`"${convertMsToTime(sentence.start)}"`);
        break;
      case 'End Time':
        data.push(`"${convertMsToTime(sentence.end)}"`);
        break;
      case 'Speaker':
        data.push(`"${sentence.speaker}"`);
        break;
      case 'isQuestion':
        data.push(`"${sentence.isQuestion}"`);
        break;
      case 'Type':
        data.push(`"${sentence.label}"`);
        break;
      case 'Text':
        data.push(`"${sentence.trim().replace(/"/g, '""')}"`);
        break;
    }
  }
  return data.join(', ');
}
```

2023-11-01 04:46 UTC, J4ninja commented on frontend/src/Main/Submission/submission.js
> +      if (startTimeBox && push) {
We can't return early. push is used for the individual checkbox whether we will add that element in the csv. It's really  to prevent pushing things when Only Questions is checked which means that when it is a question, we will push the element based off other checkboxes. Push is overridden for every sentence. But maybe we can use "continue" if js has it so we can skip this sentence to get what you meant. I could break up the function into multiple smaller functions if you would like.

2023-11-01 14:13 UTC, J4ninja commented
Task: Add dropdown or make "Only Questions" clear

2023-11-01 14:15 UTC, J4ninja commented on frontend/src/Main/Submission/submission.js
> +        if (sentences[index].isQuestion)
Consider doing early continue or filter before

2023-11-03 15:08 UTC, J4ninja commented on frontend/src/Main/Submission/submission.js
> +      if (startTimeBox && push) {
Now using helper functions

2023-11-03 15:18 UTC, jhmejia commented on frontend/src/Main/Submission/submission.js
> +            <label className="checkBox">Only Include Questions<input type="checkbox" className="checkBox" checked={questionsBox} onChange={() => setQuestionsBox(!questionsBox)}></input></label>
<select className="dropdown" value={questionsBox ? "questions" : "fullTranscript"} onChange={(e) => setQuestionsBox(e.target.value === "questions")}>
  <option value="fullTranscript">Include Full Transcript</option>
  <option value="questions">Only Include Questions</option>
</select>

2023-11-03 15:36 UTC, J4ninja commented on frontend/src/Main/Submission/submission.js
> +            <label className="checkBox">Only Include Questions<input type="checkbox" className="checkBox" checked={questionsBox} onChange={() => setQuestionsBox(!questionsBox)}></input></label>
added

2023-11-03 15:59 UTC, jhmejia approved these changes

2023-11-05 19:10 UTC, merged