Added side Menu and new page for File List
TCU-Instructional-AI/classifAI pull request #9
Opened 2023-10-29 20:26 UTC by nagato0519

## Type of Change
UI/UX update

## Context
To make it more dashboard-like.
To organize the files

## Changes Made
Added Side Menu
Added new page to List (not designed yet)
Updated the URL Paths

## Screenshots
<img width="2560" alt="Screenshot 2023-10-29 at 3 25 54 PM" src="https://github.com/TCU-Instructional-AI/classifAI/assets/66901230/ef079d84-ce3f-4c1a-b95a-01b3133041aa">

## Checklist

- [ ] I have tested these changes locally
- [ ] I have updated the documentation, if applicable
- [ ] I have added unit tests, if applicable

2023-10-30 21:40 UTC, jhmejia requested changes

2023-10-30 21:40 UTC, jhmejia commented on frontend/src/Layout/Layout.js
> +                                {/* menu when user is not signed in */}
When I am logged out, pressing 'home' brings up the navbar menu. From there, clicking account brings me a runtime error. 

Is this intended behavior? I am not sure if this is a future bug that will be fixed because we're ignoring login status, or something else? 

![image](https://github.com/TCU-Instructional-AI/classifAI/assets/29128358/58b360b6-1b6e-4d93-ae02-22eb544ca606)

2023-10-30 21:51 UTC, nagato0519 commented on frontend/src/Layout/Layout.js
> +                                {/* menu when user is not signed in */}
Yes, this error is because I am ignoring the login status for now. I can fix it easily.
In the future, if you log out, the navbar won't have an "account" option in the navbar and will send you back to the landing page anyway.

2023-10-31 02:09 UTC, J4ninja commented on frontend/src/Layout/Layout.js
> +                                {/* menu when user is not signed in */}
Sign out button appears based on login now. That error shouldn't be reachable if they go through the normal login process. In the future, we still need page url security. The error can be replicated if they mess with the urls. LGTM now.

2023-11-01 02:55 UTC, merged